{
 "title": "Coroot namespace",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(group by (container_id,namespace,service) (label_replace(label_replace(label_set(container_restarts_total{container_id!=\"\"},\"namespace\",\"system.slice\"),\"namespace\",\"$1\",\"container_id\",\"\\\\/.+?\\\\/(.+?)\\\\/.*\"),\"service\",\"$1\",\"container_id\",\".*\\\\/(.+?)$\")))"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "query_result(group by (container_id) (container_restarts_total{container_id=~\".+?${namespace}\\\\/.+?$\"}))"
    }
   },
   {
    "name": "excl_namespace",
    "query": {
     "query": "query_result(group by (container_id,namespace,service) (label_replace(label_replace(label_set(container_restarts_total{container_id!=\"\"},\"namespace\",\"system.slice\"),\"namespace\",\"$1\",\"container_id\",\"\\\\/.+?\\\\/(.+?)\\\\/.*\"),\"service\",\"$1\",\"container_id\",\".*\\\\/(.+?)$\")))"
    }
   },
   {
    "name": "top",
    "label": "Лимит результатов на панелях (дефолт 50)",
    "query": "50"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Title\n\n1. Добавить информацию по инстансам network\n2. для cm не работает фильтр по неймспейсу\n4. добавить дропы контейнеров вне куба?\n5. надо подумать по system.slice и как их декомпозировать на графе\n5. делаем topk\n6. сделать проблемы в виде фильтра"
   }
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "group by (container_id,namespace,service) (label_replace(label_replace(label_set(container_restarts_total{container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?\\\\/$service$\"},\"namespace\",\"system.slice\"),\"namespace\",\"$1\",\"container_id\",\"\\\\/.+?\\\\/(.+?)\\\\/.*\"),\"service\",\"$1\",\"container_id\",\".*\\\\/(.+?)$\"))\n#group by (container_id,application_type) (container_application_type{container_id=~\".+?calico-node$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by (container_id,application_type) (container_application_type{container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?\\\\/$service$\"})\n#group by (container_id,application_type) (container_application_type{container_id=~\".+?calico-node$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "#range_sum(increase(sum by (container_id) (container_http_requests_total{ status!=\"200\",container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])/(range_sum(increase(sum by (container_id) (container_http_requests_total{status!=\"200\",container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])+range_sum(increase(sum by (container_id) (container_http_requests_total{ status=\"200\",container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range]) ) \nWITH (\n  metric = max by (source, actual_destination,status) (\n    label_replace(\n      sum by (container_id, actual_destination) (rate(container_http_requests_total{container_id=~\"\\\\/k8s.*\", status!~\"2..\"})[1m0s])/ on(container_id, actual_destination) sum by (container_id, actual_destination) (rate(container_http_requests_total{container_id=~\"\\\\/k8s.*\"})[1m0s]),\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n     sum by (container_id, actual_destination) ( rate(container_http_requests_total{container_id=~\"\\\\/system.*\", status!~\"2..\"})[1m0s])/ on(container_id, actual_destination) sum by (container_id, actual_destination) (rate(container_http_requests_total{container_id=~\"\\\\/system.*\"})[1m0s]),\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            #coroot:http_requests{source_namespace=~\"metricsedge\", source_service=~\".*\", target_namespace!~\"(monitoring|system\\\\.slice)\"} or on (source_pod,actual_destination) я думаю мы не смотрим вокруг выбранного нса\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\nmax by (container_id) ((metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query) * on(target_pod) group_left(container_id)\ngroup by (target_pod,container_id) (\n    label_replace(\n        container_restarts_total{container_id=~\"\\\\/k.*\"},\n        \"target_pod\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or on (target_pod,container_id) label_replace(\n        container_restarts_total{container_id=~\"\\\\/system.*\"},\n        \"target_pod\", \"$1\", \"container_id\", \"\\\\/sys.+?\\\\/(.+?)$\"\n    )\n    ))",
     "legendFormat": "errors"
    },
    {
     "expr": "#max_over_time(histogram_quantile(0.95, sum by (le, container_id)(    rate( container_http_requests_duration_seconds_total_bucket{container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"}[$__interval]))    )[$__range])\n\nWITH (\n  metric = max by (source, actual_destination) (\n    label_replace(\n      max_over_time(histogram_quantile(0.95, sum by (le, container_id,actual_destination)(\n    rate( container_http_requests_duration_seconds_total_bucket[$__interval]))\n    )[$__range]),\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n     max_over_time(histogram_quantile(0.95, sum by (le, container_id,actual_destination)(\n    rate( container_http_requests_duration_seconds_total_bucket[$__interval]))\n    )[$__range]),\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            #coroot:http_requests{source_namespace=~\"metricsedge\", source_service=~\".*\", target_namespace!~\"(monitoring|system\\\\.slice)\"} or on (source_pod,actual_destination) я думаю мы не смотрим вокруг выбранного нса\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\nmax by (container_id) ((metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query) * on(target_pod) group_left(container_id)\ngroup by (target_pod,container_id) (\n    label_replace(\n        container_restarts_total{container_id=~\"\\\\/k.*\"},\n        \"target_pod\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or on (target_pod,container_id) label_replace(\n        container_restarts_total{container_id=~\"\\\\/system.*\"},\n        \"target_pod\", \"$1\", \"container_id\", \"\\\\/sys.+?\\\\/(.+?)$\"\n    )\n    ))",
     "legendFormat": "response time 95%%"
    },
    {
     "expr": "range_sum(increase(sum by (container_id) (container_restarts_total{ container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "errors"
    },
    {
     "expr": "range_max(rate(max by (container_id) (container_resources_cpu_throttled_seconds_total{ container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "errors"
    },
    {
     "expr": "range_sum(increase(sum by (container_id) (container_oom_kills_total{ container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "oom"
    },
    {
     "expr": "range_max(increase(max by (container_id) (container_resources_disk_delay_seconds_total{ container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "oom"
    },
    {
     "expr": "range_max(increase(max by (container_id) (container_net_latency_seconds{ container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "oom"
    },
    {
     "expr": "range_max(increase(max by (container_id) (container_net_tcp_retransmits_total{ container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "oom"
    },
    {
     "expr": "range_sum(increase(sum by (container_id) (container_log_messages_total{level=\"error\", container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])/range_sum(increase(sum by (container_id) (container_log_messages_total{ container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "oom"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Все соединения выбранного объекта (дропы только у кубовых сущностей)",
   "type": "nodeGraph",
   "description": "График покажет активные соединения относительно объекта или существующие в рамках периода выбранного на дашборде. \nОн находит любые исходящие соединения объекта. Внутри показывает объем дропов пакетов в абсолютных величинах\nОн находит входящие соединения только при условии что они были от объектов которые мониторятся корутом.",
   "gridPos": { "h": 49, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "WITH( \n    base_query = alias(\n    union(\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n        ),\n        (\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n            )\n        )\n    )\n,\"nodes\") )\n\nalias(base_query * on(id) group_right(title,subtitle,__name__) range_sum(\n    sum by (id) (\n      label_copy(\n        increase(\n          container_network_advance_tcp_stats_total{tcp_state=~\".*drop\"}[1m]\n        )\n        ,\"pod\",\"id\"\n      )\n    ) \n  [$__range]\n) or (base_query - 1),\"nodes\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "\nWITH (\n  metric = max by (source, actual_destination,target,id) (\n        label_replace(\n          rate(container_net_tcp_retransmits_total{container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n        ) or \n        label_replace(\n          rate(container_net_tcp_retransmits_total{container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n            \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n        )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service,target,id)(\n    label_join(\n      label_replace(\n          label_copy(\n              coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n              or on (source_pod,actual_destination)\n              coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n              \"source_pod\",\"source\",\"target_pod\",\"target\"\n          ),\n          \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n      ),\n      \"id\",\"+\",\"source\",\"target\"\n    )\n  )\n)\n\nalias(label_set(\n  max by (id,source,target) (\n   label_join(\n      label_copy(\n          (metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service,target,id) edges_query) >0\n      ,\"target_pod\",\"target\")\n  ,\"id\",\"+\",\"source\",\"target\"))\n,\"color\",\"red\",\"highlighted\",\"true\")\nor on (id,source,target) max by (id,source,target,color,highlighted) (\n  label_set(edges_query,\"color\",\"\",\"highlighted\",\"false\") * 0\n),\"edges\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network round-trip time, seconds (показаны $top самых долгих откликов)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, destination_ip) (\n    label_replace(\n      increase(container_net_latency_seconds{container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      increase(container_net_latency_seconds{container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,destination_ip,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"destination_ip\",\"$1\",\"actual_destination\",\"(.+?):.*\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,destination_ip) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "TCP connection latency, seconds (показаны $top самых долгих откликов)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "\n\nWITH (\n  metric = max by (source, destination) (\n      label_replace(\n        increase(container_net_tcp_connection_time_seconds_total{container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        increase(container_net_tcp_connection_time_seconds_total{container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "Active TCP connections (показаны $top количественных сессий)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination) (\n      label_replace(\n        (container_net_tcp_active_connections{container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n         \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        (container_net_tcp_active_connections{container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n           \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "TCP connection attempts, per second (не уверен что правильно считаю) (показаны $top самых частотных сессий)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination) (\n      label_replace(\n        rate(container_net_tcp_active_connections{container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n         \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        rate(container_net_tcp_active_connections{container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n           \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "Traffic outboud/inboud bytes/sec (показаны $top самых объемных взаимодействий)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "\n\n\nWITH (\n  metric = max by (source, actual_destination) (\n      label_replace(\n        increase(container_net_tcp_bytes_received_total{container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        increase(container_net_tcp_bytes_received_total{container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "recv: {{source}} -> [{{target_namespace}}] {{target_pod}}"
    },
    {
     "expr": "\n\n\nWITH (\n  metric = max by (source, actual_destination) (\n      label_replace(\n        increase(container_net_tcp_bytes_sent_total{container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        increase(container_net_tcp_bytes_sent_total{container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "sent: {{source}} -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "TCP retransmissions, segments/second (показаны $top самых частотных взаимодействий)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "\nWITH (\n  metric = max by (source, actual_destination) (\n      label_replace(\n        rate(container_net_tcp_retransmits_total{container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n         \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        rate(container_net_tcp_retransmits_total{container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n           \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))\n",
     "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "TCP drops, packets/second (если 0 то может не быть метрик) (показаны $top количественных узлов)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "WITH( \n    base_query = alias(\n    union(\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n        ),\n        (\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n            )\n        )\n    )\n,\"nodes\") )\n\ntopk_max($top,alias(base_query * on(id) group_right(title,subtitle,__name__) \n    sum by (id) (\n      label_copy(\n        increase(\n          container_network_advance_tcp_stats_total{tcp_state=~\".*drop\"}[1m]\n        )\n        ,\"pod\",\"id\"\n      )\n    ) \n  ,\"nodes\"))",
     "legendFormat": "{{id}} {{title}} {{subtitle}}"
    }
   ]
  },
  {
   "title": "Прикладной слой (HTTP/Databases/Kafka/Cache)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 }
  },
  {
   "title": "Все соединения выбранного объекта (error%)",
   "type": "nodeGraph",
   "description": "График покажет активные соединения относительно объекта или существующие в рамках периода выбранного на дашборде. \nОн находит любые исходящие соединения объекта. Внутри показывает объем дропов пакетов в абсолютных величинах\nОн находит входящие соединения только при условии что они были от объектов которые мониторятся корутом.",
   "gridPos": { "h": 35, "w": 7, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "WITH( \n    base_query = alias(\n    union(\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:http_requests{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n        ),\n        (\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:http_requests{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n            )\n        )\n    )\n,\"nodes\") )\n\n\nalias(\n    base_query * on(id) group_right(title,subtitle,__name__) \n    range_max(\n        max by (id) (\n            label_copy(\n                max by (container_id,actual_destination) (\n                    rate(container_http_requests_duration_seconds_total_sum{container_id=~\"\\\\/k8s.*\"})/rate(container_http_requests_duration_seconds_total_count{container_id=~\"\\\\/k8s.*\"})\n                ) * on(container_id,actual_destination) group_left(target_pod) group by (container_id,actual_destination,target_pod) (coroot:http_requests),\n                \"target_pod\",\"id\"\n            ) or\n            label_copy(\n                max by (container_id,actual_destination) (\n                    rate(container_http_requests_duration_seconds_total_sum{container_id=~\"\\\\/system.*\"})/rate(container_http_requests_duration_seconds_total_count{container_id=~\"\\\\/system.*\"})\n                )  * on(container_id,actual_destination) group_left(target_pod) group by (container_id,actual_destination,target_pod) (coroot:http_requests),\n                \"target_pod\",\"id\"\n            )\n        )\n    ) \n  [$__range]\n or (base_query - 1),\"nodes\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "alias(\n    group by(source,target,id)(\n        label_join(\n            label_copy(\n                coroot:http_requests{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"} \n                or\n                coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n                \"source_pod\",\"source\",\"target_pod\",\"target\"\n            ),\n            \"id\",\"+\",\"source\",\"target\"\n        )\n    )\n,\"edges\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Response time (показаны $top самых высоких откликов)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination) (\n    label_replace(\n      rate(container_http_requests_duration_seconds_total_sum{container_id=~\"\\\\/k8s.*\"})/rate(container_http_requests_duration_seconds_total_count{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_http_requests_duration_seconds_total_sum{container_id=~\"\\\\/k8s.*\"})/rate(container_http_requests_duration_seconds_total_count{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:http_requests{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "HTTP Request per second (all codes) (показаны $top самых частых запросов)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination) (\n    label_replace(\n      rate(container_http_requests_duration_seconds_total_count{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_http_requests_duration_seconds_total_count{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:http_requests{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "HTTP Request per second (200-ые коды) (показаны $top самых частых запросов)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination,status) (\n    label_replace(\n      rate(container_http_requests_total{container_id=~\"\\\\/k8s.*\", status=~\"2..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_http_requests_total{container_id=~\"\\\\/k8s.*\", status=~\"2..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:http_requests{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} (code:{{status}}) -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "HTTP Request per second (400-ые коды) (показаны $top самых частых запросов)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination,status) (\n    label_replace(\n      rate(container_http_requests_total{container_id=~\"\\\\/k8s.*\", status=~\"4..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_http_requests_total{container_id=~\"\\\\/k8s.*\", status=~\"4..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:http_requests{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} (code:{{status}}) -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "HTTP Request per second (500-ые коды) (показаны $top самых частых запросов)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination,status) (\n    label_replace(\n      rate(container_http_requests_total{container_id=~\"\\\\/k8s.*\", status=~\"5..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_http_requests_total{container_id=~\"\\\\/k8s.*\", status=~\"5..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:http_requests{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} (code:{{status}}) -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  { "title": "Statefulls in progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Все соединения выбранного объекта (дропы только у кубовых сущностей)",
   "type": "nodeGraph",
   "description": "График покажет активные соединения относительно объекта или существующие в рамках периода выбранного на дашборде. \nОн находит любые исходящие соединения объекта. Внутри показывает объем дропов пакетов в абсолютных величинах\nОн находит входящие соединения только при условии что они были от объектов которые мониторятся корутом.",
   "gridPos": { "h": 49, "w": 7, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "WITH( \n    base_query = alias(\n    union(\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n        ),\n        (\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n            )\n        )\n    )\n,\"nodes\") )\n\nalias(base_query * on(id) group_right(title,subtitle,__name__) range_sum(\n    sum by (id) (\n      label_copy(\n        increase(\n          container_network_advance_tcp_stats_total{tcp_state=~\".*drop\"}[1m]\n        )\n        ,\"pod\",\"id\"\n      )\n    ) \n  [$__range]\n) or (base_query - 1),\"nodes\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "\nWITH (\n  metric_fail = max by (source, actual_destination,target,id) (\n        label_replace(\n          rate(container_postgres_queries_total{container_id=~\"\\\\/k8s.*\",status!=\"ok\"})[$__rate_interval],\n          \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n        ) or label_replace(\n          rate(container_postgres_queries_total{container_id=~\"\\\\/system.slice.*\",status!=\"ok\"})[$__rate_interval],\n          \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n        )\n  ),\n  metric_good = max by (source, actual_destination,target,id) (\n        label_replace(\n          rate(container_postgres_queries_total{container_id=~\"\\\\/k8s.*\",status=\"ok\"})[$__rate_interval],\n          \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n        ) or label_replace(\n          rate(container_postgres_queries_total{container_id=~\"\\\\/system.slice.*\",status=\"ok\"})[$__rate_interval],\n          \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n        )\n  ),  \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service,target,id)(\n    label_join(\n      label_replace(\n          label_copy(\n              coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n              or on (source_pod,actual_destination)\n              coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n              \"source_pod\",\"source\",\"target_pod\",\"target\"\n          ),\n          \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n      ),\n      \"id\",\"+\",\"source\",\"target\"\n    )\n  )\n)\n\nalias(\n  label_set(\n  max by (id,source,target) (\n   label_join(\n      label_copy(\n          (metric_fail * on(source,actual_destination) group_left(target_namespace,target_pod,target_service,target,id) edges_query) \n      ,\"target_pod\",\"target\")\n  ,\"id\",\"+\",\"source\",\"target\"))\n,\"color\",\"red\",\"highlighted\",\"true\")\nor on (id,source,target) \nmax by (id,source,target,color,highlighted) (\n  label_set(\n    max by (id,source,target) (\n      label_join(\n        label_copy( \n          (metric_good * on(source,actual_destination) group_left(target_namespace,target_pod,target_service,target,id) edges_query)\n        ,\"target_pod\",\"target\")\n      ,\"id\",\"+\",\"source\",\"target\")\n    )\n  ,\"color\",\"\",\"highlighted\",\"false\") \n),\"edges\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres query duration time (показаны $top самых высоких откликов)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination) (\n    label_replace(\n      rate(container_postgres_queries_duration_seconds_total_sum{container_id=~\"\\\\/k8s.*\"})/rate(container_postgres_queries_duration_seconds_total_count{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_postgres_queries_duration_seconds_total_sum{container_id=~\"\\\\/k8s.*\"})/rate(container_postgres_queries_duration_seconds_total_count{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "Postgresql requests (показаны $top самых частых запросов)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination,status) (\n    label_replace(\n      rate(container_postgres_queries_total{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_postgres_queries_total{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} (code:{{status}}) -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "Postgresql FAILED requests (показаны $top самых частых запросов)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination,status) (\n    label_replace(\n      rate(container_postgres_queries_total{container_id=~\"\\\\/k8s.*\", status!=\"ok\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_postgres_queries_total{container_id=~\"\\\\/k8s.*\", status!=\"ok\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} (code:{{status}}) -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "Kafka query duration time (показаны $top самых высоких откликов)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination) (\n    label_replace(\n      rate(container_kafka_requests_duration_seconds_total_sum{container_id=~\"\\\\/k8s.*\"})/rate(container_kafka_requests_duration_seconds_total_count{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_kafka_requests_duration_seconds_total_sum{container_id=~\"\\\\/k8s.*\"})/rate(container_kafka_requests_duration_seconds_total_count{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  {
   "title": "Kafka requests (показаны $top самых частых запросов)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination,status) (\n    label_replace(\n      rate(container_kafka_requests_total{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_kafka_requests_total{container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
     "legendFormat": "{{source}} (code:{{status}}) -> [{{target_namespace}}] {{target_pod}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "WITH( \n    base_query = alias(\n    union(\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n        ),\n        (\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n            )\n        )\n    )\n,\"nodes\") )\n\nalias(base_query * on(id) group_right(title,subtitle,__name__) \n    sum by (id,sample,level,pattern_hash) (\n      label_replace(\n        increase(\n          sum by (sample,level,pattern_hash,container_id) (rate(container_log_messages_total{container_id=~\"\\\\/k8s.*\", sample!=\"\"})) >0[1m]\n        )\n        ,\"id\",\"$1\",\"container_id\",\"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      )\n    ) \n  ,\"nodes\")\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs (показаны $top самых частотных логов)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 160 },
   "targets": [
    {
     "expr": "WITH( \n    base_query = alias(\n    union(\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n        ),\n        (\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n            )\n        )\n    )\n,\"nodes\") )\n\n\ntopk_max($top,alias(base_query * on(id) group_right(title,subtitle,__name__) \n    sum by (id,sample,level,pattern_hash) (\n      label_replace(\n        increase(\n          sum by (sample,level,pattern_hash,container_id) (increase(container_log_messages_total{container_id=~\"\\\\/k8s.*\", sample!=\"\"})) >0[15s]\n        )\n        ,\"id\",\"$1\",\"container_id\",\"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      )\n    ) \n  ,\"nodes\"))\n",
     "legendFormat": "{{id}} ({{title}} {{subtitle}}) [{{level}}]: -----> {{sample}} "
    }
   ]
  }
 ]
}