{
 "title": "FQDN Outgoing Connections (Coroot)",
 "tags": [
  "security",
  "network",
  "kubernetes"
 ],
 "time": { "from": "2025-06-23T07:08:34.051Z", "to": "2025-06-23T07:09:34.051Z" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster_name)"
    }
   },
   {
    "name": "source_namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster_name=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "destination_namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster_name=\"$cluster\"},namespace)"
    }
   },
   { "name": "negative_regex" }
  ]
 },
 "panels": [
  { "title": "In-Cluster Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "In-Cluster Connections",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    label_replace(\n      label_replace(\n        container_net_tcp_successful_connects_total{cluster_name=~\"$cluster\", container_id=~\"/k8s/${source_namespace}/.*\"},\n        \"source_container\", \"$4\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n      ),\n      \"source_pod\", \"$3\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n    ),\n    \"source_namespace\", \"$2\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n  ),\n  \"source_controller\", \"$1\", \"source_pod\", \"(.+?)(-[^-]+)?$\"\n)\n* on (actual_destination, cluster_name) group_left(\n    destination_namespace,\n    destination_pod,\n    destination_container,\n    destination_ip,\n    destination_port,\n    destination_controller\n) (\n  label_replace(\n    label_replace(\n      label_replace(\n          label_replace(\n              label_replace(\n                  label_replace(\n                      label_replace(\n                          container_net_tcp_listen_info{cluster_name=~\"$cluster\", container_id=~\"/k8s/${destination_namespace}/.*\"},\n                          \"actual_destination\", \"$1\", \"listen_addr\", \"(.*)\"\n                      ),\n                      \"destination_namespace\", \"$2\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n                  ),\n                  \"destination_pod\", \"$3\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n              ),\n              \"destination_container\", \"$4\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n          ),\n          \"destination_ip\", \"$1\", \"actual_destination\", \"([^:]+):.*\"\n      ),\n      \"destination_port\", \"$1\", \"actual_destination\", \"[^:]+:([0-9]+)\"\n    ),\n  \"destination_controller\", \"$1\", \"destination_pod\", \"(.+?)(-[^-]+)?$\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-Cluster Connections (NS to NS)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    label_replace(\n      label_replace(\n        container_net_tcp_successful_connects_total{cluster_name=~\"$cluster\", container_id=~\"/k8s/${source_namespace}/.*\"},\n        \"source_container\", \"$4\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n      ),\n      \"source_pod\", \"$3\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n    ),\n    \"source_namespace\", \"$2\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n  ),\n  \"source_controller\", \"$1\", \"source_pod\", \"(.+?)(-[^-]+)?$\"\n)\n* on (actual_destination, cluster_name) group_left(\n    destination_namespace,\n    destination_pod,\n    destination_container,\n    destination_ip,\n    destination_port,\n    destination_controller\n) (\n  label_replace(\n    label_replace(\n      label_replace(\n          label_replace(\n              label_replace(\n                  label_replace(\n                      label_replace(\n                          container_net_tcp_listen_info{cluster_name=~\"$cluster\", container_id=~\"/k8s/${destination_namespace}/.*\"},\n                          \"actual_destination\", \"$1\", \"listen_addr\", \"(.*)\"\n                      ),\n                      \"destination_namespace\", \"$2\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n                  ),\n                  \"destination_pod\", \"$3\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n              ),\n              \"destination_container\", \"$4\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n          ),\n          \"destination_ip\", \"$1\", \"actual_destination\", \"([^:]+):.*\"\n      ),\n      \"destination_port\", \"$1\", \"actual_destination\", \"[^:]+:([0-9]+)\"\n    ),\n  \"destination_controller\", \"$1\", \"destination_pod\", \"(.+?)(-[^-]+)?$\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Outgoing Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Outgoing Connections (by NS)",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "group by (cluster_name, source_namespace, source_pod, source_container, source_controller, destination_ip, destination_port) (\n  label_replace(\n    label_replace(\n      label_replace(\n        label_replace(\n          label_replace(\n            label_replace(\n            container_net_tcp_successful_connects_total{\n                cluster_name=~\"$cluster\", container_id=~\"/k8s/${source_namespace}/.*\",\n            },\n            \"destination_ip\", \"$1\", \"actual_destination\", \"([^:]+):.*\"\n            ),\n            \"destination_port\", \"$1\", \"actual_destination\", \"[^:]+:([0-9]+)\"\n          ),\n          \"source_container\", \"$4\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n        ),\n        \"source_pod\", \"$3\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n      ),\n      \"source_namespace\", \"$2\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n    ),\n    \"source_controller\", \"$1\", \"source_pod\", \"(.+?)(-[^-]+)?$\"\n  )\n)\n* on (destination_ip, cluster_name) group_left(fqdn) (\n  group by (cluster_name, destination_ip, fqdn) (\n    label_replace(\n        topk(1, ip_to_fqdn{cluster_name=~\"$cluster\"}) by (ip),\n        \"destination_ip\", \"$1\", \"ip\", \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Connections (by NS, external FQDN)",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 24 },
   "targets": [
    {
     "expr": "group by (cluster_name, source_namespace, source_pod, source_container, source_controller, destination_ip, destination_port) (\n  label_replace(\n    label_replace(\n      label_replace(\n        label_replace(\n          label_replace(\n            label_replace(\n            container_net_tcp_successful_connects_total{\n                cluster_name=~\"$cluster\", container_id=~\"/k8s/${source_namespace}/.*\",\n            },\n            \"destination_ip\", \"$1\", \"actual_destination\", \"([^:]+):.*\"\n            ),\n            \"destination_port\", \"$1\", \"actual_destination\", \"[^:]+:([0-9]+)\"\n          ),\n          \"source_container\", \"$4\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n        ),\n        \"source_pod\", \"$3\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n      ),\n      \"source_namespace\", \"$2\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n    ),\n    \"source_controller\", \"$1\", \"source_pod\", \"(.+?)(-[^-]+)?$\"\n  )\n)\n* on (destination_ip, cluster_name) group_left(fqdn) (\n  group by (cluster_name, destination_ip, fqdn) (\n    label_replace(\n        topk(1, ip_to_fqdn{cluster_name=~\"$cluster\", fqdn!~\"$negative_regex\"}) by (ip),\n        \"destination_ip\", \"$1\", \"ip\", \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uniq external FQDN",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    group by (cluster_name, source_namespace, source_pod, source_container, source_controller, destination_ip, destination_port) (\n  label_replace(\n    label_replace(\n      label_replace(\n        label_replace(\n          label_replace(\n            label_replace(\n            container_net_tcp_successful_connects_total{\n                cluster_name=~\"$cluster\", container_id=~\"/k8s/${source_namespace}/.*\",\n            },\n            \"destination_ip\", \"$1\", \"actual_destination\", \"([^:]+):.*\"\n            ),\n            \"destination_port\", \"$1\", \"actual_destination\", \"[^:]+:([0-9]+)\"\n          ),\n          \"source_container\", \"$4\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n        ),\n        \"source_pod\", \"$3\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n      ),\n      \"source_namespace\", \"$2\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n    ),\n    \"source_controller\", \"$1\", \"source_pod\", \"(.+?)(-[^-]+)?$\"\n  )\n)\n* on (destination_ip, cluster_name) group_left(fqdn) (\n  group by (cluster_name, destination_ip, fqdn) (\n    label_replace(\n        topk(1, ip_to_fqdn{cluster_name=~\"$cluster\", fqdn!~\"$negative_regex\"}) by (ip),\n        \"destination_ip\", \"$1\", \"ip\", \"(.*)\"\n    )\n  )\n),\n    \"domain\", \"$2$3\", \"fqdn\", \"(.*\\\\.)?([^.]+\\\\.)([^.]+)$\"\n  ),\n  \"subdomain\", \"$1\", \"fqdn\", \"(.*)\\\\.([^.]+\\\\.)([^.]+)$\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Connections",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "group by (cluster_name, source_namespace, source_pod, source_container, source_controller, destination_ip, destination_port) (\n  label_replace(\n    label_replace(\n      label_replace(\n        label_replace(\n          label_replace(\n            label_replace(\n            container_net_tcp_successful_connects_total{\n                cluster_name=~\"$cluster\", container_id=~\"/k8s/${source_namespace}/.*\",\n            },\n            \"destination_ip\", \"$1\", \"actual_destination\", \"([^:]+):.*\"\n            ),\n            \"destination_port\", \"$1\", \"actual_destination\", \"[^:]+:([0-9]+)\"\n          ),\n          \"source_container\", \"$4\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n        ),\n        \"source_pod\", \"$3\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n      ),\n      \"source_namespace\", \"$2\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n    ),\n    \"source_controller\", \"$1\", \"source_pod\", \"(.+?)(-[^-]+)?$\"\n  )\n)\n* on (destination_ip, cluster_name) group_left(fqdn) (\n  group by (cluster_name, destination_ip, fqdn) (\n    label_replace(\n        topk(1, ip_to_fqdn{cluster_name=~\"$cluster\"}) by (ip),\n        \"destination_ip\", \"$1\", \"ip\", \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Listen Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Listen Info - coroot",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    label_replace(\n      label_replace(\n        label_replace(\n          container_net_tcp_listen_info{cluster_name=~\"$cluster\", container_id=~\"/k8s/${source_namespace}/.*\"},\n          \"source_container\", \"$4\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n        ),\n        \"source_pod\", \"$3\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n      ),\n      \"source_namespace\", \"$2\", \"container_id\", \"/([^/]+)/([^/]+)/([^/]+)/([^/]+)\"\n    ),\n    \"ip\", \"$1\", \"listen_addr\", \"([^:]+):.*\"\n  ),\n  \"port\", \"$1\", \"listen_addr\", \"[^:]+:([0-9]+)\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "kube_endpoint_address{cluster_name=~\"$cluster\", namespace=~\"$source_namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Listen Info - System Services",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n          container_net_tcp_listen_info{cluster_name=~\"$cluster\", container_id=~\"/system.slice/.*\", listen_addr=~\"(\\\\d{1,3}\\\\.){3}\\\\d{1,3}:\\\\d+\"},\n    \"ip\", \"$1\", \"listen_addr\", \"([^:]+):.*\"\n  ),\n  \"port\", \"$1\", \"listen_addr\", \"[^:]+:([0-9]+)\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Coroot Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "System Services Success Connections",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    label_replace(\n      label_replace(\n              container_net_tcp_successful_connects_total{\n                cluster_name=~\"$cluster\", container_id=~\"/system.slice/.*\"\n              },\n        \"actual_ip\", \"$1\", \"actual_destination\", \"([^:]+):.*\"\n      ),\n      \"actual_port\", \"$1\", \"actual_destination\", \"[^:]+:([0-9]+)\"\n    ),\n    \"ip\", \"$1\", \"destination\", \"([^:]+):.*\"\n  ),\n  \"port\", \"$1\", \"destination\", \"[^:]+:([0-9]+)\"\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}